version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: roottoor
      POSTGRES_DB: tgbotmessages
    ports:
      - "5430:5432"
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  
  bot:
    build:
      context: ./
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: roottoor
      DB_NAME: tgbotmessages
      RABBITMQ_URL: rabbitmq://rabbitmq:5672/

    depends_on:
      - postgres
      - rabbitmq